# Generated by Django 6.0.4 on 2026-04-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restourant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="years_for_experience",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
