# Generated by Django 6.0.4 on 2026-04-25 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restourant", "0002_alter_cook_years_for_experience"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cook",
            old_name="years_for_experience",
            new_name="years_or_experience",
        ),
    ]
