# Generated by Django 6.0.4 on 2026-04-25 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restourant", "0003_rename_years_for_experience_cook_years_or_experience"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cook",
            old_name="years_or_experience",
            new_name="years_of_experience",
        ),
    ]
